### DISCUSSION TITLE
Trusted certificate instead of letsencrypt?

### DISCUSSION THREAD

**Discussion by uncltom** [docusealco/docuseal#184] [Q&A] [answered]
We purchased a cert for our domain pointing to DocuSeal and we would like the domain to use that cert instead of letsencrypt.
Is this possible?

**Comment by omohokcoj** [comment, marked as answer]
@uncltom 

```yaml
version: '3'

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal

  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - .:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /path/to/your/certs:/certs # replace it with path to your certs on disk
```


^ Replace your existing docker-compose file with the file above.

In:
```
    volumes:
      - .:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /path/to/your/certs:/certs # replace it with path to your certs on disk
```
Replace `/path/to/your/certs`

---

Create `Caddyfile` in the same folder with `docker-compose.yml`:

```
yourdomain.com {
  reverse_proxy * {
    to app:3000
  }
  tls /certs/yourdomain.crt /certs/yourdomain.key
}
```

Replace `yourdomain.com` with your custom domain name (or subdomain).
Replace `tls /certs/yourdomain.crt /certs/yourdomain.key` with the name of your cert files: /certs is a shared folder in docker which links to the folder with your certs on disk.


---

Run `docker-compose up --force-recreate`
