### DISCUSSION TITLE
Run multiple instances of Docuseal (prod/dev) ?

### DISCUSSION THREAD

**Discussion by apcloic** [docusealco/docuseal#188] [Q&A] [answered]
Hi,
I'm not familiar with Docker and Caddy, does anybody know th best way run another instance of Docuseal using a subdomain on the same VPS for test/development purpose ?
Regards,

**Comment by omohokcoj** [comment, marked as answer]
@apcloic you need to create Caddyfile with two subdomains - here is an example Caddy file: https://github.com/docusealco/docuseal/discussions/184#discussioncomment-8073098
```
yourdomain.com {
  reverse_proxy * {
    to app:3000
  }
}
staging.yourdomain.com {
  reverse_proxy * {
    to stagingapp:3000
  }
}
```

and then in docker-compose define a second docuseal `stagingapp` service with staging psotgresql

**Comment by apcloic** [comment]
@omohokcoj

Thanks a lot for your help ! 
Regarding docker-compose, it should look like this ?
No risk to mess with the data on disk between app and staging_app ?

docker_compose.yml

````
version: '3'

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal

  staging_app:
    depends_on:
      staging_postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal


  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  staging_postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - .:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
   
````

Caddyfile

````
mydomain.com {
  reverse_proxy * {
    to app:3000
  }
}
staging.mydomain.com {
  reverse_proxy * {
    to staging_app:3000
  }
}

````

Regards,

**Comment by omohokcoj** [comment]
@apcloic you need to update staging mounted directories to make sure the data won't be shared between apps:
![image](https://github.com/docusealco/docuseal/assets/5418788/f3b38cb0-db17-4027-8788-d978b12e01d4)

**Reply by apcloic** [reply]
@omohokcoj Thank you very much 👌

**Reply by apcloic** [reply]
@omohokcoj 

Almost done, last issue is :

````
Bind for 0.0.0.0:3000 failed: port is already allocated

````

So I've tried to change the port mapping in staging_app :

````

  staging_app:
    depends_on:
      staging_postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 4000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal

````

Then I run :

````
 docker compose up --force-recreate -d

````

And the issue is gone.

app is working properly but staging_app return an error 500.

So I've also tried to change Caddyfile like this :

````
staging.mydomain.com {
  reverse_proxy * {
    to staging_app:4000
  }

````

but it's worst than error 500, I get no page found error.

Any idea ?

**Reply by apcloic** [reply]
Here's the error log, I don't clearly see what's wrong...

````

[723a7c4f-90f0-4289-9205-fbb60c6e42df] lib/docuseal.rb:56:in `default_url_options'
[723a7c4f-90f0-4289-9205-fbb60c6e42df] app/controllers/application_controller.rb:30:in `default_url_options'
[723a7c4f-90f0-4289-9205-fbb60c6e42df] app/views/shared/_meta.html.erb:8
[723a7c4f-90f0-4289-9205-fbb60c6e42df] app/views/layouts/_head_tags.html.erb:4
[723a7c4f-90f0-4289-9205-fbb60c6e42df] app/views/layouts/application.html.erb:4
[723a7c4f-90f0-4289-9205-fbb60c6e42df] app/controllers/dashboard_controller.rb:80:in `maybe_render_landing'
[723a7c4f-90f0-4289-9205-fbb60c6e42df] lib/api_path_consider_json_middleware.rb:15:in `call'
I, [2024-01-16T18:06:46.830278 #1]  INFO -- : [723a7c4f-90f0-4289-9205-fbb60c6e42df] {"method":"GET","path":"/500","format":"html","controller":"ErrorsController","action":"show","status":500,"allocations":2915,"duration":3.48,"view":0.92,"db":0.0,"fwd":"XX.XXX.XXX.XXX"}
I, [2024-01-16T18:06:48.364664 #1]  INFO -- : [1d9c14a2-d822-41d1-bcc6-b33e5bfafba9] {"method":"GET","path":"/","format":"html","controller":"DashboardController","action":"index","status":500,"allocations":2171,"duration":4.58,"view":0.0,"db":0.79,"fwd":"XX.XXX.XXX.XXX"}
E, [2024-01-16T18:06:48.369910 #1] ERROR -- : [1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]   
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9] ActionView::Template::Error (ActiveRecord::Encryption::Errors::Decryption):
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]      5: <meta property="og:title" content="DocuSeal | Open Source Document Filling and Signing">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]      6: <meta property="og:description" content="Open source, self-hosted tool to streamline document filling and signing. Create custom PDF forms to complete and sign with an easy to use online tool.">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]      7: <meta property="og:type" content="website">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]      8: <meta property="og:url" content="<%= root_url %>">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]      9: <meta property="og:site_name" content="DocuSeal">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]     10: <meta property="og:image" content="<%= image_pack_url('images/preview.png') %>">
[1d9c14a2-d822-41d1-bcc6-b33e5bfafba9]     11: <meta property="og:image:width" content="800">

````

**Reply by omohokcoj** [reply]
@apcloic you need to use staging postgresql URL
![image](https://github.com/docusealco/docuseal/assets/5418788/d72e04c0-c216-4c5c-bd20-a96b565809a1)

**Reply by apcloic** [reply]
@omohokcoj you rock ! 

Everything is working as expected after setting the database_url properly like this ! 

````
  staging_app:
    depends_on:
      staging_postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 4000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@staging_postgres:5432/docuseal

````

Thanks a lot for your help.
