### DISCUSSION TITLE
Why not use a .env file and move variables from docker-compose.yml to the .env file?

### DISCUSSION THREAD

**Discussion by ovizii** [docusealco/docuseal#72] [Ideas]
Currently, the docker-compose.yml sample contains stuff like:

```
    environment:
      FORCE_SSL: 'true'
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docuseal

  postgres:
    image: postgres:latest
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
```

why don't we use a .env like:

```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=secretpassword
POSTGRES_DB=docuseal
POSTGRES_HOST=docuseal-db
POSTGRES_PORT=5432
```

and then reference those variables inside docker-compose.yml like:

```
    environment:
      FORCE_SSL: 'true'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

```

```
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

```
