### DISCUSSION TITLE
Can somebody please clarify how SMTP settings work?

### DISCUSSION THREAD

**Discussion by ovizii** [docusealco/docuseal#85] [Q&A] [answered]
I asked around and was told I can use docker variables so I have these inside my .env file:

```
SMTP_ADDRESS=10.10.10.10
SMTP_PORT=25
#SMTP_DOMAIN=
#SMTP_USERNAME=
#SMTP_PASSWORD=
SMTP_AUTHENTICATION=none
SMTP_ENABLE_STARTTLS_AUTO=false
SMTP_FROM=me@mydomain.tld

```

and these inside my docker-compose.yml file within the docuseal app:

```
    environment:
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
#      SMTP_DOMAIN: ${SMTP_DOMAIN}
#      SMTP_USERNAME: ${SMTP_USERNAME}
#      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}
      SMTP_FROM: ${SMTP_FROM}
```

I can test these settings are working by pretending I forgot my email and docuseal will send me a password reset link. 
Also, I had to comment those 3 lines as leaving them uncommented won't work.

What I still do not get is how to add/invite other people to collaborate. Within docuseal I see this warning whenever I try to do so:

![image](https://github.com/docusealco/docuseal/assets/837902/f69680f3-eb61-498e-a262-991d73ebf955)

The link: "Go to SMTP settings" leads here and gives this error when I leave the username field empty

![image](https://github.com/docusealco/docuseal/assets/837902/2ba786f7-3909-4ffa-b6e2-996cc69f1ea0)

Could somebody please help me figure this out? Are SMTP settings via -env only used for the system messages and each user needs to define his own SMTP settings? Why is it still asking for username despite: https://github.com/docusealco/docuseal/issues/23
