### ISSUE TITLE
Cannot Upload Documents

### ISSUE THREAD

**Issue by mike-lloyd03** [docusealco/docuseal#116]
I'm running the Docker version with Postgres and using Caddy for my reverse-proxy.

I can create an account and log in, but when I try to upload a document, the application hangs. The spinner on the upload drop location just spins forever. I don't see any error in the webconsole or in docker logs.

Have I configured something wrong?

docker-compose.yml:
```yaml
version: "3"

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 8100:3000
    volumes:
      - ./data:/data
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docuseal

  postgres:
    image: postgres:15
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
```
