### ISSUE TITLE
Question: How to set up docuseal with external revers proxy?

### ISSUE THREAD

**Issue by AlexNikMak** [docusealco/docuseal#222]
Hi everyone!

How do I set up docuseal?

Currently, I am using Nginx proxy manager in separate container as my main revers proxy.
In this case, I can just remove this part from docker-compose.yml file?

`caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from $HOST --to app:3000
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - .:/data
    environment:
      - HOST=${HOST}`
      - 
And router port 3000 to my Nginx proxy manager?

`services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
      - FORCE_SSL=${HOST}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal`

Sorry if this question is dumb, I am not very familiar with this.

Thanks in advance.

**Comment by gabviv73** [comment]
Hy,
my 2 cents: this is the simplest docker-compose.yml to use with an external reverse proxy.
Define a proxy host with name "site.example.com" and forward port 8911 to the ip address of the docker host running the container:

```
version: '3'

services:
  app:
    image: docuseal/docuseal:latest
    ports:
      - 8911:3000
    volumes:
      - ./data:/data
    environment:
      - FORCE_SSL=site.example.com
```
