### ISSUE TITLE
Error 500 after updating to latest image

### ISSUE THREAD

**Issue by nascherer** [docusealco/docuseal#293]
Hello there,

I use the self-hosted docker version of docuseal and until now it worked like a charm for me.
 just recently updated to version 1.6.0, but when I try to open the webpage, i receive "DocuSeal: [Error] 500 - We're sorry, but somethin went wrong."
 I run docuseal on an ubuntu vps server. As proxy service i use traefik 2.0 and for database I use postgreSQL. I did not change any settings in my docker-compose.yml. I just stopped the docuseal stack in portainer and the "updated the stack" and hit "re-pull the image" - which leads to pulling the latest image.
 
```

 `I, [2024-06-11T21:19:32.869260 #1]  INFO -- : [5addb236-1166-460a-bdfa-f87f97d689d2] {"method":"GET","path":"/","format":"html","controller":"DashboardController","action":"index","status":500,"allocations":17944,"duration":172.7,"view":0.0,"db":15.77,"fwd":"94.31.68.186"}

E, [2024-06-11T21:19:32.876300 #1] ERROR -- : [5addb236-1166-460a-bdfa-f87f97d689d2]   

[5addb236-1166-460a-bdfa-f87f97d689d2] ActionView::Template::Error (ActiveRecord::Encryption::Errors::Decryption):

[5addb236-1166-460a-bdfa-f87f97d689d2]      7: <meta property="og:title" content="<%= title %>">

[5addb236-1166-460a-bdfa-f87f97d689d2]      8: <meta property="og:description" content="<%= description %>">

[5addb236-1166-460a-bdfa-f87f97d689d2]      9: <meta property="og:type" content="website">

[5addb236-1166-460a-bdfa-f87f97d689d2]     10: <meta property="og:url" content="<%= root_url %>">

[5addb236-1166-460a-bdfa-f87f97d689d2]     11: <meta property="og:site_name" content="DocuSeal">

[5addb236-1166-460a-bdfa-f87f97d689d2]     12: <% unless content_for(:disable_image_preview) %>

[5addb236-1166-460a-bdfa-f87f97d689d2]     13:   <meta property="og:image" content="<%= image_pack_url('images/preview.png') %>">

[5addb236-1166-460a-bdfa-f87f97d689d2]   

[5addb236-1166-460a-bdfa-f87f97d689d2] lib/docuseal.rb:78:in `default_url_options'

[5addb236-1166-460a-bdfa-f87f97d689d2] app/controllers/application_controller.rb:40:in `default_url_options'

[5addb236-1166-460a-bdfa-f87f97d689d2] app/views/shared/_meta.html.erb:10

[5addb236-1166-460a-bdfa-f87f97d689d2] app/views/layouts/_head_tags.html.erb:4

[5addb236-1166-460a-bdfa-f87f97d689d2] app/views/layouts/application.html.erb:4

[5addb236-1166-460a-bdfa-f87f97d689d2] app/controllers/dashboard_controller.rb:42:in `maybe_render_landing'

[5addb236-1166-460a-bdfa-f87f97d689d2] lib/api_path_consider_json_middleware.rb:15:in `call'

[5addb236-1166-460a-bdfa-f87f97d689d2] lib/normalize_client_ip_middleware.rb:14:in `call'

I, [2024-06-11T21:19:32.907919 #1]  INFO -- : [5addb236-1166-460a-bdfa-f87f97d689d2] {"method":"GET","path":"/500","format":"html","controller":"ErrorsController","action":"show","status":500,"allocations":2911,"duration":4.58,"view":1.12,"db":0.0,"fwd":"94.31.68.186"}`

```

This is how my docker-compose.yml for docuseal looks like. at the moment

```
version: '3.9'
services:
  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:latest
    ports:
      - 3013:3000
    volumes:
      - /home/docker_admin/docker/docuseal/data:/data
    environment:
      - DATABASE_URL=postgresql://MYUSERNAME:MYPASSWORD@postgres:5432/docuseal
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docuseal.rule=Host(`docuseal.myhomepage.duckdns.org`)"
      - "traefik.http.routers.docuseal.entrypoints=https"
      - "traefik.http.routers.docuseal.tls.certresolver=duckdns"
      - "traefik.http.routers.docuseal.tls=true"

networks:
  traefik-proxy:
    external: true
```
is it necessary to put a RAILS_MASTER_KEY in the latest version of docuseal?

If i try to log into the postgres database via command line from within the docuseal container
```
psql -h localhost -U USERNAME -d docuseal
```
i can reach all the tables ...

Does anyone have an idea?
