### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by nemanjastanic** [docusealco/docuseal#364]
Hello! I'm unable to start DocuSeal with Docker. Is this a known issue?

```
docuseal  | Puma starting in single mode...
docuseal  | * Puma version: 6.4.2 (ruby 3.3.4-p94) ("The Eagle of Durango")
docuseal  | *  Min threads: 15
docuseal  | *  Max threads: 15
docuseal  | *  Environment: production
docuseal  | *          PID: 1
docuseal  | WARNING: Nokogiri was built against libxml version 2.12.9, but has dynamically loaded 2.12.7
docuseal  | ! Unable to load application: NoMethodError: undefined method `has_many_inversing=' for class ActiveRecord::Base
docuseal  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
docuseal  | /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_many_inversing=' for class ActiveRecord::Base (NoMethodError)
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/railtie.rb:292:in `block (3 levels) in <class:Railtie>'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/railtie.rb:282:in `each'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/railtie.rb:282:in `block (2 levels) in <class:Railtie>'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `each'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/base.rb:15:in `<main>'
docuseal  |     from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
docuseal  |     from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
docuseal  |     from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
docuseal  |     from /usr/local/bundle/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/tasks/database_tasks.rb:506:in `migration_class'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/tasks/database_tasks.rb:510:in `migration_connection'
docuseal  |     from /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
docuseal  |     from /app/config/initializers/migrate.rb:4:in `block in <main>'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:448:in `instance_exec'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:448:in `block in make_lambda'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `catch'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `block in default_terminator'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:203:in `block in halting'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `block in invoke_before'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `each'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `invoke_before'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:109:in `run_callbacks'
docuseal  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:96:in `prepare!'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
docuseal  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'
docuseal  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'
docuseal  |     from /app/config/environment.rb:7:in `<top (required)>'
docuseal  |     from config.ru:3:in `require_relative'
docuseal  |     from config.ru:3:in `block (2 levels) in <top (required)>'
docuseal  |     from /usr/local/bundle/gems/rack-3.1.7/lib/rack/builder.rb:108:in `eval'
docuseal  |     from /usr/local/bundle/gems/rack-3.1.7/lib/rack/builder.rb:108:in `new_from_string'
docuseal  |     from /usr/local/bundle/gems/rack-3.1.7/lib/rack/builder.rb:97:in `load_file'
docuseal  |     from /usr/local/bundle/gems/rack-3.1.7/lib/rack/builder.rb:67:in `parse_file'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:368:in `load_rackup'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:290:in `app'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/runner.rb:162:in `load_and_bind'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/single.rb:44:in `run'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/lib/puma/cli.rb:75:in `run'
docuseal  |     from /usr/local/bundle/gems/puma-6.4.2/bin/puma:10:in `<top (required)>'
docuseal  |     from /usr/local/bundle/bin/puma:25:in `load'
docuseal  |     from /usr/local/bundle/bin/puma:25:in `<top (required)>'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
docuseal  |     from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
docuseal  |     from /app/bin/bundle:108:in `load'
docuseal  |     from /app/bin/bundle:108:in `<main>'
```

Here's my `docker-compose.yml`:
```yaml
services:
  docuseal:
    restart: unless-stopped
    container_name: docuseal
    image: docuseal/docuseal:latest
    hostname: docuseal
    environment:
      - PUID=1000
      - PGID=1000
      - FORCE_SSL=bleh
      - DATABASE_URL=postgresql://bleh:bleh@docuseal-postgres:5432/docuseal
    networks:
      - bleh
    labels:
      traefik.enable: true
      traefik.http.routers.docuseal-http.entrypoints: web
      traefik.http.routers.docuseal-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.docuseal-http.rule: Host(`bleh`)
      traefik.http.routers.docuseal-http.service: docuseal
      traefik.http.routers.docuseal.entrypoints: websecure
      traefik.http.routers.docuseal.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.docuseal.rule: Host(`bleh`)
      traefik.http.routers.docuseal.service: docuseal
      traefik.http.routers.docuseal.tls.certresolver: cfdns
      traefik.http.routers.docuseal.tls.options: securetls@file
      traefik.http.services.docuseal.loadbalancer.server.port: 3000
    volumes:
      - ./docuseal:/data/docuseal

networks:
  bleh:
    external: true
```
