### ISSUE TITLE
Login failed after updating to 1.9.4 docker

### ISSUE THREAD

**Issue by gabviv73** [docusealco/docuseal#447]
After updating to latest, no more logins are allowed.
No reset password works.
Using embedded db, no postgres.

No useful logs for me in logging in:

`sign.example.com-app-1  | I, [2025-03-07T17:09:35.030320 #1]  INFO -- : [0bf65f84-6eda-48e5-ae3c-3e99f5e2249b] {"method":"GET","format":"html","controller":"PasswordsController","action":"new","status":200,"allocations":2036,"duration":94.89,"view":13.55,"db":0.21,"fwd":"1.2.3.4","params":{},"host":"sign.example.com","uid":null}
sign.example.com-app-1  | I, [2025-03-07T17:09:35.956780 #1]  INFO -- : [9016b5ae-fc75-4f86-a873-9d5182aad327] {"method":"POST","format":"turbo_stream","controller":"SessionsController","action":"create","status":0,"allocations":913,"duration":360.32,"view":0.0,"db":0.47,"fwd":"1.2.3.4","params":{},"host":"sign.example.com","uid":null}
sign.example.com-app-1  | I, [2025-03-07T17:09:36.115728 #1]  INFO -- : [9016b5ae-fc75-4f86-a873-9d5182aad327] {"method":"POST","format":"turbo_stream","controller":"SessionsController","action":"new","status":200,"allocations":2647,"duration":131.86,"view":29.03,"db":0.04,"fwd":"1.2.3.4","params":{},"host":"sign.example.com","uid":null}

`

**Comment by omohokcoj** [comment]
@gabviv73 are you using docuseal/docuseal image? maybe you use CDN/reverse proxy over the app which clears session cookies

**Comment by gabviv73** [comment]
Hy,
I'm using docuseal/docuseal:latest image. 
I've always used a reverse proxy, nothing changed. Only upgraded image.
Here is docker-compose.yml

```
services:
  sign.rvmgroup.it-app:
    image: docuseal/docuseal:latest
    restart: unless-stopped
    ports:
      - 8911:3000
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - FORCE_SSL=sign.example.com
      - HOST=sign.example.com
```

**Comment by gabviv73** [comment]
Same behaviour accessing directly using the ip address of the docker host on port 8911 using this docker-compose.yml:

```
services:
  sign.example.com-app:
    image: docuseal/docuseal:latest
    restart: unless-stopped
    ports:
      - 8911:3000
    volumes:
      - ./docuseal:/data/docuseal
```
