### ISSUE TITLE
Form event webhook submission created_at has incorrect format

### ISSUE THREAD

**Issue by lenardchristopher** [docusealco/docuseal#453]
```yaml
[...]
"submission": {
        "id": 1400884,
        "created_at": "2025-03-11 18:05:30 UTC",
        "audit_log_url": "<omitted>",
        "combined_document_url": null,
        "status": "completed",
        "url": "<omitted>"
      }
[...]
```

Notice that "created_at" is not the normal date format. This is the except from the documentation:
```yaml
[...]
"submission": {
      "id": 12,
      "audit_log_url": "https://docuseal.com/blobs/proxy/eyJfcmFpbHMiOnsib/audit-log.pdf",
      "combined_document_url": "https://docuseal.com/blobs/proxy/eyJfcmFpbHMiOnsib/document.pdf",
      "status": "completed",
      "url": "https://docuseal.com/e/N5JsdkFGPeQF7J",
      "created_at": "2023-08-20T10:09:05.258Z"
    },
[...]
```
