### ISSUE TITLE
Support old kernel (or how about using ruby 3.0.*)

### ISSUE THREAD

**Issue by webysther** [docusealco/docuseal#90]
This error only happens on synology DS716 and for the same OS version on DS918 works the image, for me is something related to limitations of hardware and incompat with muslc but I can't confirm because only alpine image is provided.

```
/usr/local/lib/ruby/3.2.0/securerandom.rb:55:in `urandom': failed to get urandom (RuntimeError)
	from /usr/local/lib/ruby/3.2.0/securerandom.rb:55:in `gen_random_openssl'
	from /usr/local/lib/ruby/3.2.0/random/formatter.rb:74:in `random_bytes'
	from /usr/local/lib/ruby/3.2.0/random/formatter.rb:94:in `hex'
	from /app/config/boot.rb:14:in `<top (required)>'
	from /app/bin/rails:3:in `require_relative'
	from /app/bin/rails:3:in `<main>'
```

```yml
version: "3.9"

services:
  docuseal:
    image: docuseal/docuseal
    container_name: app-sign
    expose:
      - 3000
    networks:
      docuseal:

networks:
  docuseal:
    name: docuseal
```
